### ISSUE TITLE
Error on try to execute "go run main.go"

### ISSUE THREAD

**Issue by ottroco** [alpody/golang-fiber-realworld-example-app#2]
when I try to execute the command above give:

main.go:9:2: no required module provides package github.com/alpody/fiber-realworld/docs; to add it:
        go get github.com/alpody/fiber-realworld/docs

and when to try

go get github.com/alpody/fiber-realworld/docs

ask me for a username/password

can you help me?

**Comment by alpody** [comment]
github.com/alpody/fiber-realworld/docs  is a generated package.

Try:

`go get -u github.com/swaggo/swag/cmd/swag  &&  go generate . `

and then:

`go run main.go `

Another way is using 'make' utility. Makefile has some commands to build, run, test application

**Comment by alpody** [comment]
It's not bug.
