### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by jonathan200934** [alpody/golang-fiber-realworld-example-app#3]
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/andybalholm/brotli v1.0.2
go: updates to go.mod needed; to update it:
	go mod tidy
The command '/bin/sh -c go get -u github.com/swaggo/swag/cmd/swag  &&  go generate . && GOOS=linux GOARCH=amd64 CGO_ENABLED=1  go build -ldflags='-extldflags=-static'  -o myapp .' returned a non-zero code: 1
ERROR: Service 'fiber-realworld' failed to build : Build failed

**Comment by jonathan200934** [comment]
![Screenshot from 2022-01-06 13-12-40](https://user-images.githubusercontent.com/55126160/149359456-47d13294-a772-4c5e-aa44-c8de42fc7ab9.png)

**Comment by jonathan200934** [comment]
![Screenshot from 2022-01-13 19-29-02](https://user-images.githubusercontent.com/55126160/149359526-4c404616-5bde-4305-a695-d8b448c4f8a3.png)

**Comment by alpody** [comment]
Which OS, CPU architecture have you used?

**Comment by alpody** [comment]
I can't reproduce your's issue
